#define PNGNAME2X(VEHICLENAME, CARGONAME) STR(2x/VEHICLENAME##CARGONAME.vox.png)

#define ALTERNATIVESPRITE(VEHICLENAME, CARGO, LENGTH) \
alternative_sprites(spriteset_##VEHICLENAME##CARGO, ZOOM_LEVEL_IN_2X, BIT_DEPTH_8BPP, PNGNAME2X(VEHICLENAME,CARGO)) { template_length_##LENGTH##_2x() }

#define SPRITES2X(VEHICLENAME, LENGTH)                  \
ALTERNATIVESPRITE(VEHICLENAME, , LENGTH)                \
ALTERNATIVESPRITE(VEHICLENAME, _coal, LENGTH)           \
ALTERNATIVESPRITE(VEHICLENAME, _copper, LENGTH)         \
ALTERNATIVESPRITE(VEHICLENAME, _goods, LENGTH)          \
ALTERNATIVESPRITE(VEHICLENAME, _grain, LENGTH)          \
ALTERNATIVESPRITE(VEHICLENAME, _grey, LENGTH)           \
ALTERNATIVESPRITE(VEHICLENAME, _iore, LENGTH)           \
ALTERNATIVESPRITE(VEHICLENAME, _lvst, LENGTH)           \
ALTERNATIVESPRITE(VEHICLENAME, _stel, LENGTH)           \
ALTERNATIVESPRITE(VEHICLENAME, _tanker, LENGTH)         \
ALTERNATIVESPRITE(VEHICLENAME, _timber, LENGTH)         \
ALTERNATIVESPRITE(VEHICLENAME, _wood, LENGTH)

#define SPRITES2X_WITH_FLATBED(VEHICLENAME, LENGTH)     \
SPRITES2X(VEHICLENAME, LENGTH)                          \
ALTERNATIVESPRITE(VEHICLENAME, _flatbed, LENGTH)
