#define PNGNAME4X(VEHICLENAME, CARGONAME) STR(4x/VEHICLENAME##CARGONAME.vox.png)
#define PNGNAME4X_32BPP(VEHICLENAME, CARGONAME) STR(4x_32bpp/VEHICLENAME##CARGONAME.vox.png)
#define PNGNAME4X_32BPP_MASK(VEHICLENAME, CARGONAME) STR(4x_32bpp/VEHICLENAME##CARGONAME.vox.mask.png)

#define ALTERNATIVESPRITE_4X(VEHICLENAME, CARGO, LENGTH) \
alternative_sprites(spriteset_##VEHICLENAME##CARGO, ZOOM_LEVEL_IN_4X, BIT_DEPTH_8BPP, PNGNAME4X(VEHICLENAME,CARGO)) { template_length_##LENGTH##_4x() } \
alternative_sprites(spriteset_##VEHICLENAME##CARGO, ZOOM_LEVEL_IN_4X, BIT_DEPTH_32BPP, PNGNAME4X_32BPP(VEHICLENAME,CARGO), PNGNAME4X_32BPP_MASK(VEHICLENAME,CARGO)) { template_length_##LENGTH##_4x() } \

#define SPRITES4X(VEHICLENAME, LENGTH)                  \
ALTERNATIVESPRITE_4X(VEHICLENAME, , LENGTH)                \
ALTERNATIVESPRITE_4X(VEHICLENAME, _coal, LENGTH)           \
ALTERNATIVESPRITE_4X(VEHICLENAME, _copper, LENGTH)         \
ALTERNATIVESPRITE_4X(VEHICLENAME, _goods, LENGTH)          \
ALTERNATIVESPRITE_4X(VEHICLENAME, _grain, LENGTH)          \
ALTERNATIVESPRITE_4X(VEHICLENAME, _grey, LENGTH)           \
ALTERNATIVESPRITE_4X(VEHICLENAME, _iore, LENGTH)           \
ALTERNATIVESPRITE_4X(VEHICLENAME, _lvst, LENGTH)           \
ALTERNATIVESPRITE_4X(VEHICLENAME, _stel, LENGTH)           \
ALTERNATIVESPRITE_4X(VEHICLENAME, _tanker, LENGTH)         \
ALTERNATIVESPRITE_4X(VEHICLENAME, _timber, LENGTH)         \
ALTERNATIVESPRITE_4X(VEHICLENAME, _wood, LENGTH)

#define SPRITES4X_GOODS_MAIL(VEHICLENAME, LENGTH)       \
ALTERNATIVESPRITE_4X(VEHICLENAME, , LENGTH)                \
ALTERNATIVESPRITE_4X(VEHICLENAME, _goods, LENGTH)          \
ALTERNATIVESPRITE_4X(VEHICLENAME, _mail, LENGTH)          

#define SPRITES4X_BUS(VEHICLENAME, LENGTH)              \
ALTERNATIVESPRITE_4X(VEHICLENAME, , LENGTH)                

#define SPRITES4X_WITH_FLATBED(VEHICLENAME, LENGTH)     \
ALTERNATIVESPRITE_4X(VEHICLENAME, _flatbed, LENGTH)
